name = "adare_dilithium5_examples"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Daniel Norte de Moraes"]
maintainers = ["Daniel Norte de Moraes <danieagle@tutanota.com>"]
maintainers-logins = ["danieagle"]

executables = ["adare_dilithium5_examples0", "adare_dilithium5_examples1"]
[[depends-on]]
adare_dilithium5 = "~0.2.3"
[[pins]]
adare_dilithium5 = { path='..' }

[build-switches]
"*".Ada_Version = "Ada12"
"*".Style_checks = ["-gnaty2abCefhiklnprstmM135"]
